### ref
# https://qwen.readthedocs.io/en/latest/training/SFT/llama_factory.html
# https://qwen.readthedocs.io/en/latest/getting_started/quickstart.html

### model 
model_name_or_path: unsloth/Qwen2-7B-Instruct-bnb-4bit

### method
stage: sft
do_train: true
finetuning_type: lora

#lora
quantization_bit: 4
lora_rank: 16
lora_alpha: 16 
lora_dropout: 0 
lora_target: all 

### dataset (were identity,alpaca_en_demo)
dataset: poetry_ar_3ds5
template: qwen
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2b7i/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train (1x8)
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4 # see https://github.com/hiyouga/LLaMA-Factory/issues/4614
num_train_epochs: 1.0
lr_scheduler_type: cosine
#warmup_ratio: 0.1
warmup_steps: 100
bf16: true
ddp_timeout: 180000000
optim: adamw_torch # adamw_torch, adamw_8bit or adafactor (paged_adamw_8bit good for OOM)

### eval (was 1 per dev)
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500
